-- Mobile / browser push for FLUXO notifications.
--
-- * push_subscriptions: one row per device/browser that enabled push.
-- * VAPID keys (the server's push signing identity) are generated by the
--   notifications-dispatch function on first use and kept in Vault through
--   the two service-role-only functions below — nothing to copy by hand.
-- * Every new notification is handed to notifications-dispatch right away
--   (pg_net, asynchronous) so push arrives within seconds; the five-minute
--   cron run also retries anything that was missed.
--
-- Requires 20261004120000_notifications_and_day_plan.sql. Safe to re-run.

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  last_success_at timestamptz
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users read own push subscriptions" on public.push_subscriptions;
create policy "Users read own push subscriptions"
on public.push_subscriptions for select to authenticated
using (user_id = auth.uid());

drop policy if exists "Users add own push subscriptions" on public.push_subscriptions;
create policy "Users add own push subscriptions"
on public.push_subscriptions for insert to authenticated
with check (user_id = auth.uid() and organization_id = public.current_active_organization_id());

drop policy if exists "Users remove own push subscriptions" on public.push_subscriptions;
create policy "Users remove own push subscriptions"
on public.push_subscriptions for delete to authenticated
using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- VAPID keys in Vault
-- ---------------------------------------------------------------------------
create or replace function public.read_push_vapid_keys()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  result text;
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required'; end if;
  select decrypted_secret into result from vault.decrypted_secrets where name = 'push_vapid_keys' limit 1;
  return result::jsonb;
end;
$$;
revoke all on function public.read_push_vapid_keys() from public, anon, authenticated;
grant execute on function public.read_push_vapid_keys() to service_role;

-- Stores the keys only if none exist yet, then returns whatever is stored, so
-- two concurrent first calls still end up using the same key pair.
create or replace function public.store_push_vapid_keys(keys jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if auth.role() <> 'service_role' then raise exception 'Service role required'; end if;
  perform pg_advisory_xact_lock(hashtext('push_vapid_keys'));
  if not exists (select 1 from vault.secrets where name = 'push_vapid_keys') then
    perform vault.create_secret(keys::text, 'push_vapid_keys');
  end if;
  return public.read_push_vapid_keys();
end;
$$;
revoke all on function public.store_push_vapid_keys(jsonb) from public, anon, authenticated;
grant execute on function public.store_push_vapid_keys(jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- Hand each new notification to the dispatcher for push delivery
-- ---------------------------------------------------------------------------
create or replace function public.deliver_notification_now()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  perform net.http_post(
    url := 'https://jhbpgdpllwligclpalsj.supabase.co/functions/v1/notifications-dispatch',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-notifications-secret', (
        select decrypted_secret from vault.decrypted_secrets where name = 'notifications_cron_secret' limit 1
      )
    ),
    body := jsonb_build_object('mode', 'deliver', 'notification_id', new.id),
    timeout_milliseconds := 10000
  );
  return new;
end;
$$;
revoke all on function public.deliver_notification_now() from public;

drop trigger if exists notifications_deliver_now on public.notifications;
create trigger notifications_deliver_now
after insert on public.notifications
for each row execute function public.deliver_notification_now();
